// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persona3Compendium.Web.Data;

#nullable disable

namespace Persona3Compendium.Web.Migrations
{
    [DbContext(typeof(PersonaCompendiumDbContext))]
    [Migration("20251030223301_Fix-Relations")]
    partial class FixRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Persona3Compendium.Web.Models.Arcana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Arcanas");
                });

            modelBuilder.Entity("Persona3Compendium.Web.Models.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("Persona3Compendium.Web.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArcanaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Dlc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Endurance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Luck")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Magic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArcanaId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Persona3Compendium.Web.Models.PersonaAbsorb", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonaId", "ElementId");

                    b.HasIndex("ElementId");

                    b.ToTable("PersonaAbsorb");
                });

            modelBuilder.Entity("Persona3Compendium.Web.Models.PersonaNullify", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonaId", "ElementId");

                    b.HasIndex("ElementId");

                    b.ToTable("PersonaNullify");
                });

            modelBuilder.Entity("Persona3Compendium.Web.Models.PersonaReflect", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonaId", "ElementId");

                    b.HasIndex("ElementId");

                    b.ToTable("PersonaReflect");
                });

            modelBuilder.Entity("Persona3Compendium.Web.Models.PersonaResist", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonaId", "ElementId");

                    b.HasIndex("ElementId");

                    b.ToTable("PersonaResist");
                });

            modelBuilder.Entity("Persona3Compendium.Web.Models.PersonaWeakness", b =>
                {
                    b.Property<int>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonaId", "ElementId");

                    b.HasIndex("ElementId");

                    b.ToTable("PersonaWeakness");
                });

            modelBuilder.Entity("Persona3Compendium.Web.Models.Persona", b =>
                {
                    b.HasOne("Persona3Compendium.Web.Models.Arcana", "Arcana")
                        .WithMany("Personas")
                        .HasForeignKey("ArcanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arcana");
                });

            modelBuilder.Entity("Persona3Compendium.Web.Models.PersonaAbsorb", b =>
                {
                    b.HasOne("Persona3Compendium.Web.Models.Element", "Element")
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persona3Compendium.Web.Models.Persona", "Persona")
                        .WithMany("Absorbs")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Persona3Compendium.Web.Models.PersonaNullify", b =>
                {
                    b.HasOne("Persona3Compendium.Web.Models.Element", "Element")
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persona3Compendium.Web.Models.Persona", "Persona")
                        .WithMany("Nullifies")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Persona3Compendium.Web.Models.PersonaReflect", b =>
                {
                    b.HasOne("Persona3Compendium.Web.Models.Element", "Element")
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persona3Compendium.Web.Models.Persona", "Persona")
                        .WithMany("Reflects")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Persona3Compendium.Web.Models.PersonaResist", b =>
                {
                    b.HasOne("Persona3Compendium.Web.Models.Element", "Element")
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persona3Compendium.Web.Models.Persona", "Persona")
                        .WithMany("Resists")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Persona3Compendium.Web.Models.PersonaWeakness", b =>
                {
                    b.HasOne("Persona3Compendium.Web.Models.Element", "Element")
                        .WithMany()
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persona3Compendium.Web.Models.Persona", "Persona")
                        .WithMany("Weaknesses")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Persona3Compendium.Web.Models.Arcana", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("Persona3Compendium.Web.Models.Persona", b =>
                {
                    b.Navigation("Absorbs");

                    b.Navigation("Nullifies");

                    b.Navigation("Reflects");

                    b.Navigation("Resists");

                    b.Navigation("Weaknesses");
                });
#pragma warning restore 612, 618
        }
    }
}
